name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install dotnet sdk
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.0.x
            6.0.x
            7.0.x

      - name: package
        run: dotnet pack --configuration Release --output ../packages
        working-directory: src

      - name: publish packages
        run: |
          dotnet nuget push ./packages/*.nupkg \
            --api-key=${{ secrets.GITHUB_TOKEN }} \
            --source=https://nuget.pkg.github.com/thefringeninja/index.json \
            --skip-duplicate